var bankname;
console.log("value and type of bank name before assign:",bankname, typeof bankname);
bankname = 'SBI Bank';
console.log(" value and type of bank name after initialization:", bankname, typeof bankname);
console.log("\n");
var marks = '90%';
console.log("value and type of marks:", marks, typeof marks);
console.log("\n");
var isWorking;
console.log("value and type of bank name before initialization:",isWorking, typeof isWorking);
isWorking = true;
console.log(" value and type of bank name after initialization:", isWorking, typeof isWorking);
console.log("\n");
var totalCount = "Hundred and Seven";
console.log("value and datatype of totalCount is -> :",totalCount,typeof totalCount );
 totalCount = 107;
console.log("value and datatype of totalCount is -> :",totalCount,typeof totalCount);